name = "claude-code-router"
main = "index.ts"
compatibility_date = "2025-05-30"
routes = [
  { pattern = "cc.xiaohui.cool", custom_domain = true }
]

# Enable logging
[observability]
enabled = true
head_sampling_rate = 1

# Assets configuration for static files
[assets]
directory = "./modules/best-practices/articles"
binding = "ASSETS"
